coverage:
  status:
    patch: true

comment:
  layout: "header, diff, changes, tree"
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  require_base: false # [true :: must have a base report to post]
  require_head: false
  branches:
    - master
    - test-pipeline
