name: posts_api_client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^5.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
